DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS
(
    ID        INT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA INT          NOT NULL,
    NOMBRE    VARCHAR(100) NOT NULL,
    APELLIDO  VARCHAR(100) NOT NULL
);


-- para test --
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO)
VALUES ('123456789', 'Gaston', 'Zini'),
       ('987654321', 'Pablo', 'Alzamora');